#include "K2Nodes/K2Node_GetStorage.h"

#include "BlueprintActionDatabaseRegistrar.h"
#include "BlueprintNodeSpawner.h"
#include "EdGraphSchema_K2.h"
#include "GameplayTagContainer.h"
#include "KismetCompiler.h"
#include "Blueprint/DSTypeRegistrySettings.h"
#include "DynamicStorageEditor/Public/K2Nodes/DSTypeDescriptorUtils.h"
#include "Blueprint/DSBlueprintStorageBridge.h"
#include "K2Node_CallFunction.h"

static bool TryParseGameplayTagString(
    const FString& InRawValue,
    FGameplayTag& OutTag
)
{
    FString RawValue = InRawValue;
    RawValue.TrimStartAndEndInline();

    if (RawValue.IsEmpty())
    {
        return false;
    }

    FString ExtractedTag = RawValue;

    const FString Prefix = TEXT("TagName=\"");
    const int32 PrefixIndex = RawValue.Find(Prefix);

    if (PrefixIndex != INDEX_NONE)
    {
        const int32 TagStart = PrefixIndex + Prefix.Len();

        const int32 TagEnd = RawValue.Find(
            TEXT("\""),
            ESearchCase::CaseSensitive,
            ESearchDir::FromStart,
            TagStart
        );

        if (TagEnd != INDEX_NONE && TagEnd > TagStart)
        {
            ExtractedTag = RawValue.Mid(TagStart, TagEnd - TagStart);
        }
    }

    ExtractedTag.TrimStartAndEndInline();

    OutTag = FGameplayTag::RequestGameplayTag(
        FName(*ExtractedTag),
        false
    );

    return OutTag.IsValid();
}

static bool ExtractGameplayTagFromPin(
    UEdGraphPin* TagPin,
    FGameplayTag& OutTag
)
{
    if (!TagPin)
    {
        return false;
    }

    if (TryParseGameplayTagString(TagPin->DefaultValue, OutTag))
    {
        return true;
    }

    if (TryParseGameplayTagString(TagPin->AutogeneratedDefaultValue, OutTag))
    {
        return true;
    }

    if (TagPin->LinkedTo.Num() > 0 && TagPin->LinkedTo[0])
    {
        UEdGraphPin* LinkedPin = TagPin->LinkedTo[0];

        if (TryParseGameplayTagString(LinkedPin->DefaultValue, OutTag))
        {
            return true;
        }

        if (TryParseGameplayTagString(LinkedPin->AutogeneratedDefaultValue, OutTag))
        {
            return true;
        }

        UEdGraphNode* LinkedNode = LinkedPin->GetOwningNode();

        if (!LinkedNode)
        {
            return false;
        }

        for (UEdGraphPin* NodePin : LinkedNode->Pins)
        {
            if (!NodePin)
            {
                continue;
            }

            if (TryParseGameplayTagString(NodePin->DefaultValue, OutTag))
            {
                return true;
            }

            if (TryParseGameplayTagString(NodePin->AutogeneratedDefaultValue, OutTag))
            {
                return true;
            }
        }
    }

    return false;
}

static FName ResolveGetStorageFunction(
    const FEdGraphPinType& PinType
)
{
    const FName Category = PinType.PinCategory;

    if (PinType.ContainerType != EPinContainerType::None)
    {
        return GET_FUNCTION_NAME_CHECKED(
            UDSBlueprintStorageBridge,
            RetrievePropertyData
        );
    }

    if (PinType.PinCategory == UEdGraphSchema_K2::PC_Struct)
    {
        return GET_FUNCTION_NAME_CHECKED(
            UDSBlueprintStorageBridge,
            RetrievePropertyData
        );
    }

    if (Category == UEdGraphSchema_K2::PC_Boolean)
    {
        return GET_FUNCTION_NAME_CHECKED(
            UDSBlueprintStorageBridge,
            RetrieveBoolData
        );
    }

    if (Category == UEdGraphSchema_K2::PC_Int)
    {
        return GET_FUNCTION_NAME_CHECKED(
            UDSBlueprintStorageBridge,
            RetrieveIntData
        );
    }
    
    if (Category == UEdGraphSchema_K2::PC_Int64)
    {
        return GET_FUNCTION_NAME_CHECKED(
            UDSBlueprintStorageBridge,
            RetrieveInt64Data
        );
    }

    if (Category == UEdGraphSchema_K2::PC_Real)
    {
        if (PinType.PinSubCategory == UEdGraphSchema_K2::PC_Double)
        {
            return GET_FUNCTION_NAME_CHECKED(
                UDSBlueprintStorageBridge,
                RetrieveDoubleData
            );
        }

        return GET_FUNCTION_NAME_CHECKED(
            UDSBlueprintStorageBridge,
            RetrieveFloatData
        );
    }

    if (Category == UEdGraphSchema_K2::PC_Float)
    {
        return GET_FUNCTION_NAME_CHECKED(
            UDSBlueprintStorageBridge,
            RetrieveFloatData
        );
    }

    if (Category == UEdGraphSchema_K2::PC_String)
    {
        return GET_FUNCTION_NAME_CHECKED(
            UDSBlueprintStorageBridge,
            RetrieveStringData
        );
    }

    if (Category == UEdGraphSchema_K2::PC_Name)
    {
        return GET_FUNCTION_NAME_CHECKED(
            UDSBlueprintStorageBridge,
            RetrieveNameData
        );
    }

    if (Category == UEdGraphSchema_K2::PC_Text)
    {
        return GET_FUNCTION_NAME_CHECKED(
            UDSBlueprintStorageBridge,
            RetrieveTextData
        );
    }

    if (
        Category == UEdGraphSchema_K2::PC_Byte ||
        Category == UEdGraphSchema_K2::PC_Enum
    )
    {
        return GET_FUNCTION_NAME_CHECKED(
            UDSBlueprintStorageBridge,
            RetrieveByteData
        );
    }

    if (Category == UEdGraphSchema_K2::PC_Object)
    {
        return GET_FUNCTION_NAME_CHECKED(
            UDSBlueprintStorageBridge,
            RetrieveObjectData
        );
    }

    if (Category == UEdGraphSchema_K2::PC_Class)
    {
        return GET_FUNCTION_NAME_CHECKED(
            UDSBlueprintStorageBridge,
            RetrieveClassData
        );
    }

    return NAME_None;
}

const FName UK2Node_GetStorage::ExecPinName(TEXT("Execute"));
const FName UK2Node_GetStorage::ThenPinName(TEXT("Then"));
const FName UK2Node_GetStorage::WorldContextPinName(TEXT("WorldContextObject"));
const FName UK2Node_GetStorage::TagPinName(TEXT("Tag"));
const FName UK2Node_GetStorage::ValuePinName(TEXT("Value"));

void UK2Node_GetStorage::AllocateDefaultPins()
{
    CreatePin(
        EGPD_Input,
        UEdGraphSchema_K2::PC_Exec,
        ExecPinName
    );

    CreatePin(
        EGPD_Output,
        UEdGraphSchema_K2::PC_Exec,
        ThenPinName
    );

    UEdGraphPin* WorldContextPin = CreatePin(
        EGPD_Input,
        UEdGraphSchema_K2::PC_Object,
        UObject::StaticClass(),
        WorldContextPinName
    );

    if (WorldContextPin)
    {
        WorldContextPin->bHidden = false;
        WorldContextPin->PinFriendlyName = FText::FromString(TEXT("World Context Object"));
    }

    CreatePin(
        EGPD_Input,
        UEdGraphSchema_K2::PC_Struct,
        FGameplayTag::StaticStruct(),
        TagPinName
    );

    CreatePin(
        EGPD_Output,
        UEdGraphSchema_K2::PC_Wildcard,
        ValuePinName
    );
    
    RefreshOutputType();
}

FText UK2Node_GetStorage::GetNodeTitle(ENodeTitleType::Type TitleType) const
{
    return FText::FromString(TEXT("Get Storage"));
}

FText UK2Node_GetStorage::GetTooltipText() const
{
    return FText::FromString(TEXT("Retrieves data from Dynamic Storage using a GameplayTag."));
}

FText UK2Node_GetStorage::GetMenuCategory() const
{
    return FText::FromString(TEXT("Dynamic Storage"));
}

void UK2Node_GetStorage::GetMenuActions(
    FBlueprintActionDatabaseRegistrar& ActionRegistrar
) const
{
    UClass* ActionKey = GetClass();

    if (ActionRegistrar.IsOpenForRegistration(ActionKey))
    {
        UBlueprintNodeSpawner* NodeSpawner =
            UBlueprintNodeSpawner::Create(GetClass());

        check(NodeSpawner);

        ActionRegistrar.AddBlueprintAction(ActionKey, NodeSpawner);
    }
}

void UK2Node_GetStorage::ExpandNode(
    FKismetCompilerContext& CompilerContext,
    UEdGraph* SourceGraph
)
{
    Super::ExpandNode(CompilerContext, SourceGraph);

    UEdGraphPin* ExecPin = FindPinChecked(ExecPinName);
    UEdGraphPin* ThenPin = FindPinChecked(ThenPinName);
    UEdGraphPin* WorldContextPin = FindPinChecked(WorldContextPinName);
    UEdGraphPin* TagPin = FindPinChecked(TagPinName);
    UEdGraphPin* ValuePin = FindPinChecked(ValuePinName);

    RefreshOutputType();

    if (ValuePin->PinType.PinCategory == UEdGraphSchema_K2::PC_Wildcard)
    {
        CompilerContext.MessageLog.Error(
            *FString(TEXT("Get Storage requires a registered literal Tag with known type metadata. @@")),
            this
        );

        BreakAllNodeLinks();
        return;
    }

    FName TargetFunctionName =
        ResolveGetStorageFunction(ValuePin->PinType);

    if (TargetFunctionName == NAME_None)
    {
        CompilerContext.MessageLog.Error(
            *FString::Printf(
                TEXT("Get Storage does not support this output type yet: [%s]. @@"),
                *ValuePin->PinType.PinCategory.ToString()
            ),
            this
        );

        BreakAllNodeLinks();
        return;
    }

    UK2Node_CallFunction* CallNode =
        CompilerContext.SpawnIntermediateNode<UK2Node_CallFunction>(
            this,
            SourceGraph
        );

    CallNode->FunctionReference.SetExternalMember(
        TargetFunctionName,
        UDSBlueprintStorageBridge::StaticClass()
    );

    CallNode->AllocateDefaultPins();

    CompilerContext.MovePinLinksToIntermediate(
        *ExecPin,
        *CallNode->GetExecPin()
    );

    CompilerContext.MovePinLinksToIntermediate(
        *ThenPin,
        *CallNode->GetThenPin()
    );

    CompilerContext.MovePinLinksToIntermediate(
        *WorldContextPin,
        *CallNode->FindPinChecked(TEXT("WorldContextObject"))
    );

    CompilerContext.MovePinLinksToIntermediate(
        *TagPin,
        *CallNode->FindPinChecked(TEXT("Tag"))
    );

    if (
        TargetFunctionName ==
        GET_FUNCTION_NAME_CHECKED(UDSBlueprintStorageBridge, RetrievePropertyData)
    )
    {
        UEdGraphPin* DataPin = CallNode->FindPinChecked(TEXT("Data"));

        // CustomThunk output pin must be forced to the real output type.
        DataPin->PinType = ValuePin->PinType;

        CompilerContext.MovePinLinksToIntermediate(
            *ValuePin,
            *DataPin
        );
    }
    else
    {
        UEdGraphPin* ReturnPin = CallNode->GetReturnValuePin();

        if (!ReturnPin)
        {
            CompilerContext.MessageLog.Error(
                *FString(TEXT("Get Storage internal bridge function has no return value. @@")),
                this
            );

            BreakAllNodeLinks();
            return;
        }

        // Enum output uses byte bridge function, but output pin should remain enum type.
        if (
            TargetFunctionName ==
            GET_FUNCTION_NAME_CHECKED(UDSBlueprintStorageBridge, RetrieveByteData)
        )
        {
            ReturnPin->PinType = ValuePin->PinType;
        }

        CompilerContext.MovePinLinksToIntermediate(
            *ValuePin,
            *ReturnPin
        );
    }

    BreakAllNodeLinks();
}

void UK2Node_GetStorage::RefreshOutputType()
{
    UEdGraphPin* TagPin = FindPin(TagPinName);
    UEdGraphPin* ValuePin = FindPin(ValuePinName);

    if (!TagPin || !ValuePin)
    {
        return;
    }

    FGameplayTag ResolvedTag;

    if (!ExtractGameplayTagFromPin(TagPin, ResolvedTag))
    {
        ValuePin->PinType.ResetToDefaults();
        ValuePin->PinType.PinCategory = UEdGraphSchema_K2::PC_Wildcard;

        if (GetGraph())
        {
            GetGraph()->NotifyGraphChanged();
        }

        return;
    }

    FDSTypeDescriptor Descriptor;

    if (!UDSTypeRegistrySettings::FindTypeDescriptor(
        ResolvedTag,
        Descriptor
    ))
    {
        ValuePin->PinType.ResetToDefaults();
        ValuePin->PinType.PinCategory = UEdGraphSchema_K2::PC_Wildcard;

        if (GetGraph())
        {
            GetGraph()->NotifyGraphChanged();
        }

        return;
    }

    FEdGraphPinType NewPinType;

    if (!FDSTypeDescriptorUtils::ToPinType(
        Descriptor,
        NewPinType
    ))
    {
        ValuePin->PinType.ResetToDefaults();
        ValuePin->PinType.PinCategory = UEdGraphSchema_K2::PC_Wildcard;

        if (GetGraph())
        {
            GetGraph()->NotifyGraphChanged();
        }

        return;
    }

    ValuePin->PinType = NewPinType;

    if (GetGraph())
    {
        GetGraph()->NotifyGraphChanged();
    }
}

void UK2Node_GetStorage::PinDefaultValueChanged(
    UEdGraphPin* Pin
)
{
    Super::PinDefaultValueChanged(Pin);

    if (Pin && Pin->PinName == TagPinName)
    {
        RefreshOutputType();
    }
}

void UK2Node_GetStorage::NotifyPinConnectionListChanged(
    UEdGraphPin* Pin
)
{
    Super::NotifyPinConnectionListChanged(Pin);

    if (Pin && Pin->PinName == TagPinName)
    {
        RefreshOutputType();
    }
}

void UK2Node_GetStorage::PostReconstructNode()
{
    Super::PostReconstructNode();

    RefreshOutputType();
}

void UK2Node_GetStorage::ValidateNodeDuringCompilation(
    FCompilerResultsLog& MessageLog
) const
{
    Super::ValidateNodeDuringCompilation(MessageLog);

    const UEdGraphPin* TagPin = FindPin(TagPinName);
    const UEdGraphPin* ValuePin = FindPin(ValuePinName);

    if (!TagPin)
    {
        MessageLog.Error(
            *FString(TEXT("Get Storage: Missing Tag pin. @@")),
            this
        );

        return;
    }

    if (!ValuePin)
    {
        MessageLog.Error(
            *FString(TEXT("Get Storage: Missing Value output pin. @@")),
            this
        );

        return;
    }

    FGameplayTag ResolvedTag;

    if (!ExtractGameplayTagFromPin(
        const_cast<UEdGraphPin*>(TagPin),
        ResolvedTag
    ))
    {
        MessageLog.Error(
            *FString(TEXT("Get Storage: Tag must be a compile-time known tag. Use a direct tag value or Make Literal Gameplay Tag. Dynamic tag variables cannot infer output pin type. @@")),
            this
        );

        return;
    }

    FDSTypeDescriptor Descriptor;

    if (!UDSTypeRegistrySettings::FindTypeDescriptor(
        ResolvedTag,
        Descriptor
    ))
    {
        MessageLog.Error(
            *FString::Printf(
                TEXT("Get Storage: No type metadata found for Tag [%s]. Use Set Storage once with this tag, or register the tag/type from C++ in editor/PIE. @@"),
                *ResolvedTag.ToString()
            ),
            this
        );

        return;
    }

    if (!Descriptor.IsBlueprintSupported())
    {
        MessageLog.Error(
            *FString::Printf(
                TEXT("Get Storage: Tag [%s] stores a C++-only type and cannot be used by Blueprint Get Storage. @@"),
                *ResolvedTag.ToString()
            ),
            this
        );

        return;
    }

    FEdGraphPinType ExpectedPinType;

    if (!FDSTypeDescriptorUtils::ToPinType(
        Descriptor,
        ExpectedPinType
    ))
    {
        MessageLog.Error(
            *FString::Printf(
                TEXT("Get Storage: Failed to rebuild Blueprint pin type for Tag [%s]. @@"),
                *ResolvedTag.ToString()
            ),
            this
        );

        return;
    }

    if (ValuePin->PinType.PinCategory == UEdGraphSchema_K2::PC_Wildcard)
    {
        MessageLog.Error(
            *FString::Printf(
                TEXT("Get Storage: Output pin for Tag [%s] is still wildcard. Refresh the node, reselect the tag, or compile after registry metadata exists. @@"),
                *ResolvedTag.ToString()
            ),
            this
        );

        return;
    }
}