#include "K2Nodes/K2Node_SetStorage.h"

#include "BlueprintActionDatabaseRegistrar.h"
#include "BlueprintNodeSpawner.h"
#include "EdGraphSchema_K2.h"
#include "GameplayTagContainer.h"
#include "KismetCompiler.h"
#include "K2Node_CallFunction.h"
#include "Engine/Blueprint.h"

#include "Blueprint/DSBlueprintStorageBridge.h"
#include "Blueprint/DSTypeRegistrySettings.h"
#include "K2Nodes/DSTypeDescriptorUtils.h"

const FName UK2Node_SetStorage::ExecPinName(TEXT("Execute"));
const FName UK2Node_SetStorage::ThenPinName(TEXT("Then"));
const FName UK2Node_SetStorage::WorldContextPinName(TEXT("WorldContextObject"));
const FName UK2Node_SetStorage::TagPinName(TEXT("Tag"));
const FName UK2Node_SetStorage::ValuePinName(TEXT("Value"));


// =====================================================
// GameplayTag extraction helpers
// =====================================================

static bool TryParseGameplayTagString(
    const FString& InRawValue,
    FGameplayTag& OutTag
)
{
    FString RawValue = InRawValue;
    RawValue.TrimStartAndEndInline();

    if (RawValue.IsEmpty())
    {
        return false;
    }

    FString ExtractedTag = RawValue;

    // Common FGameplayTag default format:
    // (TagName="Test.Some.Tag")
    const FString Prefix = TEXT("TagName=\"");
    const int32 PrefixIndex = RawValue.Find(Prefix);

    if (PrefixIndex != INDEX_NONE)
    {
        const int32 TagStart = PrefixIndex + Prefix.Len();

        const int32 TagEnd = RawValue.Find(
            TEXT("\""),
            ESearchCase::CaseSensitive,
            ESearchDir::FromStart,
            TagStart
        );

        if (TagEnd != INDEX_NONE && TagEnd > TagStart)
        {
            ExtractedTag = RawValue.Mid(TagStart, TagEnd - TagStart);
        }
    }

    ExtractedTag.TrimStartAndEndInline();

    OutTag = FGameplayTag::RequestGameplayTag(
        FName(*ExtractedTag),
        false
    );

    return OutTag.IsValid();
}

static bool ExtractGameplayTagFromPin(
    UEdGraphPin* TagPin,
    FGameplayTag& OutTag
)
{
    if (!TagPin)
    {
        return false;
    }

    // Case 1: direct default value on Set Storage Tag pin
    if (TryParseGameplayTagString(TagPin->DefaultValue, OutTag))
    {
        return true;
    }

    if (TryParseGameplayTagString(TagPin->AutogeneratedDefaultValue, OutTag))
    {
        return true;
    }

    // Case 2: physically connected pin
    if (TagPin->LinkedTo.Num() > 0 && TagPin->LinkedTo[0])
    {
        UEdGraphPin* LinkedPin = TagPin->LinkedTo[0];

        // Sometimes value may be on linked pin itself
        if (TryParseGameplayTagString(LinkedPin->DefaultValue, OutTag))
        {
            return true;
        }

        if (TryParseGameplayTagString(LinkedPin->AutogeneratedDefaultValue, OutTag))
        {
            return true;
        }

        // Otherwise scan all pins of the connected node
        UEdGraphNode* LinkedNode = LinkedPin->GetOwningNode();

        if (!LinkedNode)
        {
            return false;
        }

        for (UEdGraphPin* NodePin : LinkedNode->Pins)
        {
            if (!NodePin)
            {
                continue;
            }

            if (TryParseGameplayTagString(NodePin->DefaultValue, OutTag))
            {
                return true;
            }

            if (TryParseGameplayTagString(NodePin->AutogeneratedDefaultValue, OutTag))
            {
                return true;
            }
        }
    }

    return false;
}


// =====================================================
// Pin allocation
// =====================================================

void UK2Node_SetStorage::AllocateDefaultPins()
{
    CreatePin(
        EGPD_Input,
        UEdGraphSchema_K2::PC_Exec,
        ExecPinName
    );

    CreatePin(
        EGPD_Output,
        UEdGraphSchema_K2::PC_Exec,
        ThenPinName
    );

    // World Context hidden pin
    UEdGraphPin* WorldContextPin = CreatePin(
        EGPD_Input,
        UEdGraphSchema_K2::PC_Object,
        UObject::StaticClass(),
        WorldContextPinName
    );

    if (WorldContextPin)
    {
        WorldContextPin->bHidden = false;
        WorldContextPin->PinFriendlyName = FText::FromString(TEXT("World Context Object"));
    }

    // GameplayTag pin
    UEdGraphPin* TagPin = CreatePin(
        EGPD_Input,
        UEdGraphSchema_K2::PC_Struct,
        FGameplayTag::StaticStruct(),
        TagPinName
    );

    if (TagPin)
    {
        TagPin->PinFriendlyName = FText::FromString(TEXT("Tag"));
    }

    // Wildcard value pin
    UEdGraphPin* ValuePin = CreatePin(
        EGPD_Input,
        UEdGraphSchema_K2::PC_Wildcard,
        ValuePinName
    );

    if (ValuePin)
    {
        ValuePin->PinFriendlyName = FText::FromString(TEXT("Value"));
    }
}


// =====================================================
// Node display
// =====================================================

FText UK2Node_SetStorage::GetNodeTitle(
    ENodeTitleType::Type TitleType
) const
{
    return FText::FromString(TEXT("Set Storage"));
}

FText UK2Node_SetStorage::GetTooltipText() const
{
    return FText::FromString(
        TEXT("Stores data in Dynamic Storage using a GameplayTag.")
    );
}

FText UK2Node_SetStorage::GetMenuCategory() const
{
    return FText::FromString(TEXT("Dynamic Storage"));
}

void UK2Node_SetStorage::GetMenuActions(
    FBlueprintActionDatabaseRegistrar& ActionRegistrar
) const
{
    UClass* ActionKey = GetClass();

    if (ActionRegistrar.IsOpenForRegistration(ActionKey))
    {
        UBlueprintNodeSpawner* NodeSpawner =
            UBlueprintNodeSpawner::Create(GetClass());

        check(NodeSpawner);

        ActionRegistrar.AddBlueprintAction(ActionKey, NodeSpawner);
    }
}

// =====================================================
// Node expansion
// =====================================================

void UK2Node_SetStorage::ExpandNode(
    FKismetCompilerContext& CompilerContext,
    UEdGraph* SourceGraph
)
{
    Super::ExpandNode(CompilerContext, SourceGraph);

    UEdGraphPin* ExecPin = FindPinChecked(ExecPinName);
    UEdGraphPin* ThenPin = FindPinChecked(ThenPinName);
    UEdGraphPin* WorldContextPin = FindPinChecked(WorldContextPinName);
    UEdGraphPin* TagPin = FindPinChecked(TagPinName);
    UEdGraphPin* ValuePin = FindPinChecked(ValuePinName);

    if (ValuePin->PinType.PinCategory == UEdGraphSchema_K2::PC_Wildcard)
    {
        CompilerContext.MessageLog.Error(
            *FString(TEXT("Set Storage requires a typed Value pin. @@")),
            this
        );

        BreakAllNodeLinks();
        return;
    }

    FName TargetFunctionName = NAME_None;

    const FEdGraphPinType& ValuePinType = ValuePin->PinType;
    const FName Category = ValuePinType.PinCategory;

    // =====================================================
    // ARRAY ROUTING ONLY
    // =====================================================

    if (ValuePinType.ContainerType == EPinContainerType::Array)
    {
        TargetFunctionName = GET_FUNCTION_NAME_CHECKED(UDSBlueprintStorageBridge, RegisterArrayData);
    }
    else if (ValuePinType.ContainerType == EPinContainerType::Set)
    {
        TargetFunctionName = GET_FUNCTION_NAME_CHECKED(UDSBlueprintStorageBridge, RegisterSetData);
    }
    
    else if (ValuePinType.ContainerType == EPinContainerType::Map)
    {
        TargetFunctionName = GET_FUNCTION_NAME_CHECKED(UDSBlueprintStorageBridge, RegisterMapData);
    }
    else
    {
        // =====================================================
        // SCALAR ROUTING
        // =====================================================

        if (Category == UEdGraphSchema_K2::PC_Boolean)
        {
            TargetFunctionName =
                GET_FUNCTION_NAME_CHECKED(
                    UDSBlueprintStorageBridge,
                    RegisterBoolData
                );
        }
        else if (Category == UEdGraphSchema_K2::PC_Int)
        {
            TargetFunctionName =
                GET_FUNCTION_NAME_CHECKED(
                    UDSBlueprintStorageBridge,
                    RegisterIntData
                );
        }
        else if (Category == UEdGraphSchema_K2::PC_Int64)
        {
            TargetFunctionName =
                GET_FUNCTION_NAME_CHECKED(
                    UDSBlueprintStorageBridge,
                    RegisterInt64Data
                );
        }
        else if (Category == UEdGraphSchema_K2::PC_Real)
        {
            if (ValuePinType.PinSubCategory == UEdGraphSchema_K2::PC_Double)
            {
                TargetFunctionName =
                    GET_FUNCTION_NAME_CHECKED(
                        UDSBlueprintStorageBridge,
                        RegisterDoubleData
                    );
            }
            else
            {
                TargetFunctionName =
                    GET_FUNCTION_NAME_CHECKED(
                        UDSBlueprintStorageBridge,
                        RegisterFloatData
                    );
            }
        }
        else if (Category == UEdGraphSchema_K2::PC_Float)
        {
            TargetFunctionName =
                GET_FUNCTION_NAME_CHECKED(
                    UDSBlueprintStorageBridge,
                    RegisterFloatData
                );
        }
        else if (Category == UEdGraphSchema_K2::PC_String)
        {
            TargetFunctionName =
                GET_FUNCTION_NAME_CHECKED(
                    UDSBlueprintStorageBridge,
                    RegisterStringData
                );
        }
        else if (Category == UEdGraphSchema_K2::PC_Name)
        {
            TargetFunctionName =
                GET_FUNCTION_NAME_CHECKED(
                    UDSBlueprintStorageBridge,
                    RegisterNameData
                );
        }
        else if (Category == UEdGraphSchema_K2::PC_Text)
        {
            TargetFunctionName =
                GET_FUNCTION_NAME_CHECKED(
                    UDSBlueprintStorageBridge,
                    RegisterTextData
                );
        }
        else if (
            Category == UEdGraphSchema_K2::PC_Byte ||
            Category == UEdGraphSchema_K2::PC_Enum
        )
        {
            TargetFunctionName =
                GET_FUNCTION_NAME_CHECKED(
                    UDSBlueprintStorageBridge,
                    RegisterByteData
                );
        }
        else if (Category == UEdGraphSchema_K2::PC_Object)
        {
            TargetFunctionName =
                GET_FUNCTION_NAME_CHECKED(
                    UDSBlueprintStorageBridge,
                    RegisterObjectData
                );
        }
        else if (Category == UEdGraphSchema_K2::PC_Class)
        {
            TargetFunctionName =
                GET_FUNCTION_NAME_CHECKED(
                    UDSBlueprintStorageBridge,
                    RegisterClassData
                );
        }
        else if (Category == UEdGraphSchema_K2::PC_Struct)
        {
            TargetFunctionName =
                GET_FUNCTION_NAME_CHECKED(
                    UDSBlueprintStorageBridge,
                    RegisterStructData
                );
        }
    }

    // =====================================================
    // Unsupported type
    // =====================================================

    if (TargetFunctionName == NAME_None)
    {
        CompilerContext.MessageLog.Error(
            *FString::Printf(
                TEXT("Set Storage does not support this Value pin type yet: [%s]. @@"),
                *Category.ToString()
            ),
            this
        );

        BreakAllNodeLinks();
        return;
    }

    // =====================================================
    // Register Type Metadata AFTER support check
    // =====================================================

    FDSTypeDescriptor Descriptor;

    if (!FDSTypeDescriptorUtils::FromPinType(ValuePinType, Descriptor))
    {
        CompilerContext.MessageLog.Error(
            *FString(TEXT("Set Storage: Unsupported type for Blueprint storage. @@")),
            this
        );

        BreakAllNodeLinks();
        return;
    }

    FGameplayTag ResolvedTag;

    if (!ExtractGameplayTagFromPin(TagPin, ResolvedTag))
    {
        CompilerContext.MessageLog.Warning(
            *FString(TEXT("Set Storage: Could not register type metadata because Tag could not be resolved at compile time. @@")),
            this
        );
    }
    else
    {
#if WITH_EDITOR
        UDSTypeRegistrySettings::RegisterTypeDescriptor(
            ResolvedTag,
            Descriptor
        );
#endif
    }

    // =====================================================
    // Spawn bridge function call
    // =====================================================

    UK2Node_CallFunction* CallNode =
        CompilerContext.SpawnIntermediateNode<UK2Node_CallFunction>(
            this,
            SourceGraph
        );

    CallNode->FunctionReference.SetExternalMember(
        TargetFunctionName,
        UDSBlueprintStorageBridge::StaticClass()
    );

    CallNode->AllocateDefaultPins();

    CompilerContext.MovePinLinksToIntermediate(
        *ExecPin,
        *CallNode->GetExecPin()
    );

    CompilerContext.MovePinLinksToIntermediate(
        *ThenPin,
        *CallNode->GetThenPin()
    );

    CompilerContext.MovePinLinksToIntermediate(
        *WorldContextPin,
        *CallNode->FindPinChecked(TEXT("WorldContextObject"))
    );

    CompilerContext.MovePinLinksToIntermediate(
        *TagPin,
        *CallNode->FindPinChecked(TEXT("Tag"))
    );

    UEdGraphPin* CallDataPin = CallNode->FindPinChecked(TEXT("Data"));

    // Only CustomThunk struct needs manual type override.
    // Normal typed functions, including arrays, already have valid UFUNCTION pin metadata.
    if (
        TargetFunctionName == GET_FUNCTION_NAME_CHECKED(UDSBlueprintStorageBridge, RegisterStructData) ||
        TargetFunctionName == GET_FUNCTION_NAME_CHECKED(UDSBlueprintStorageBridge, RegisterArrayData) ||
        TargetFunctionName == GET_FUNCTION_NAME_CHECKED(UDSBlueprintStorageBridge, RegisterSetData) ||
        TargetFunctionName == GET_FUNCTION_NAME_CHECKED(UDSBlueprintStorageBridge, RegisterMapData)
    )
    {
        CallDataPin->PinType = ValuePinType;
    }

    CompilerContext.MovePinLinksToIntermediate(
        *ValuePin,
        *CallDataPin
    );

    BreakAllNodeLinks();
}


// =====================================================
// Wildcard value pin typing
// =====================================================

void UK2Node_SetStorage::NotifyPinConnectionListChanged(
    UEdGraphPin* Pin
)
{
    Super::NotifyPinConnectionListChanged(Pin);

    if (!Pin || Pin->PinName != ValuePinName)
    {
        return;
    }

    if (Pin->LinkedTo.Num() > 0 && Pin->LinkedTo[0])
    {
        Pin->PinType = Pin->LinkedTo[0]->PinType;

        // Special handling for Self object pin.
        if (
            Pin->PinType.PinCategory == UEdGraphSchema_K2::PC_Object &&
            Pin->PinType.PinSubCategory == UEdGraphSchema_K2::PSC_Self &&
            !Pin->PinType.PinSubCategoryObject.IsValid()
        )
        {
            if (UBlueprint* Blueprint = GetBlueprint())
            {
                Pin->PinType.PinSubCategoryObject =
                    Blueprint->GeneratedClass;
            }
        }
    }
    else
    {
        Pin->PinType.PinCategory = UEdGraphSchema_K2::PC_Wildcard;
        Pin->PinType.PinSubCategory = NAME_None;
        Pin->PinType.PinSubCategoryObject = nullptr;
        Pin->PinType.ContainerType = EPinContainerType::None;
    }

    GetGraph()->NotifyGraphChanged();
}

void UK2Node_SetStorage::PostReconstructNode()
{
    Super::PostReconstructNode();

    UEdGraphPin* ValuePin = FindPin(ValuePinName);

    if (!ValuePin)
    {
        return;
    }

    if (ValuePin->LinkedTo.Num() > 0 && ValuePin->LinkedTo[0])
    {
        ValuePin->PinType = ValuePin->LinkedTo[0]->PinType;

        if (
            ValuePin->PinType.PinCategory == UEdGraphSchema_K2::PC_Object &&
            ValuePin->PinType.PinSubCategory == UEdGraphSchema_K2::PSC_Self &&
            !ValuePin->PinType.PinSubCategoryObject.IsValid()
        )
        {
            if (UBlueprint* Blueprint = GetBlueprint())
            {
                ValuePin->PinType.PinSubCategoryObject =
                    Blueprint->GeneratedClass;
            }
        }
    }
}

void UK2Node_SetStorage::ValidateNodeDuringCompilation(
    FCompilerResultsLog& MessageLog
) const
{
    Super::ValidateNodeDuringCompilation(MessageLog);

    const UEdGraphPin* TagPin = FindPin(TagPinName);
    const UEdGraphPin* ValuePin = FindPin(ValuePinName);

    if (!TagPin)
    {
        MessageLog.Error(
            *FString(TEXT("Set Storage: Missing Tag pin. @@")),
            this
        );

        return;
    }

    if (!ValuePin)
    {
        MessageLog.Error(
            *FString(TEXT("Set Storage: Missing Value pin. @@")),
            this
        );

        return;
    }

    if (ValuePin->PinType.PinCategory == UEdGraphSchema_K2::PC_Wildcard)
    {
        MessageLog.Error(
            *FString(TEXT("Set Storage: Value pin must be connected to a typed value. @@")),
            this
        );

        return;
    }

    FDSTypeDescriptor Descriptor;

    if (!FDSTypeDescriptorUtils::FromPinType(
        ValuePin->PinType,
        Descriptor
    ))
    {
        MessageLog.Error(
            *FString(TEXT("Set Storage: This value type is not supported by Dynamic Storage Blueprint storage. @@")),
            this
        );

        return;
    }

    if (!Descriptor.IsBlueprintSupported())
    {
        MessageLog.Error(
            *FString(TEXT("Set Storage: This value type is C++-only and cannot be stored through Blueprint nodes. @@")),
            this
        );

        return;
    }

    FGameplayTag ResolvedTag;

    if (!ExtractGameplayTagFromPin(
        const_cast<UEdGraphPin*>(TagPin),
        ResolvedTag
    ))
    {
        MessageLog.Warning(
            *FString(TEXT("Set Storage: Tag could not be resolved at compile time. The value can still be stored, but Blueprint Get Storage may not be able to infer its output type automatically. @@")),
            this
        );
    }
}